### PR TITLE
fix zeros not saving on text inputs

### LINKED ISSUE #1280: When opening product component number input clears zero value
Please write up one bug report OR one idea per GitHub issue. For example, if you have multiple (different) ideas, write up multiple GitHub issues.

## Bug
when a number input is given a value of zero in kiln, the input box clears when edit dialog is opened

### PR DESCRIPTION
**Pull request by rmfarrell**
`parseFloat` is causing the issue here. It's being called on an empty string. Keen handles zeros correctly without the `NaN` conversion. I could investigate that further but 🤷‍♂️ 

closes #1280

### CODE REVIEW

File: inputs/text.vue [hunk 1]
```diff
@@ -110,7 +110,8 @@
       // every time the value of the input changes, update the store
       update(val) {
         if (this.isNumerical) {
-          val = parseFloat(val, 10);
```
Comment (rmfarrell) [inline inputs/text.vue]: I 🔪 'd this `10` because I don't think `parseFloat` takes a 2nd arg(?)

Comment (nelsonpecora) [reply inputs/text.vue]: yuuup, that's `parseInt`
